import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

import '../dtos/post_dto.dart';

part 'posts_remote_data_source.g.dart';

/// Type-safe Retrofit client for the posts endpoints. The implementation is
/// generated by `retrofit_generator` into the `.g.dart` part file.
@RestApi()
abstract class PostsRemoteDataSource {
  factory PostsRemoteDataSource(Dio dio, {String? baseUrl}) =
      _PostsRemoteDataSource;

  @GET('/posts')
  Future<List<PostDto>> getPosts(
    @Query('page') int page,
    @Query('limit') int limit, {
    @CancelRequest() CancelToken? cancelToken,
  });

  @GET('/posts/{id}')
  Future<PostDto> getPost(@Path('id') int id);

  @POST('/posts')
  Future<PostDto> createPost(@Body() PostDto body);

  @PUT('/posts/{id}')
  Future<PostDto> updatePost(@Path('id') int id, @Body() PostDto body);

  @DELETE('/posts/{id}')
  Future<void> deletePost(@Path('id') int id);
}
